search/semantic-search/semantic-search-fast.ipynb
search/semantic-search/semantic-search.ipynb

New semantic search examples. One shows the data preparation process (`semantic-search.ipynb`), the other allows users to skip this using `pinecone-datasets` (`semantic-search-fast.ipynb`).
I'd propose this approach of having two parallel notebooks for _"fast"_ and not fast to be the standard for those we'd like to speed up with `pinecone-datasets`.

added new semantic search notebooks

---

generation/langchain/handbook/03-langchain-conversational-memory.ipynb

Hey a link in this example wasn't working and redirecting to the respective page in langchain docs.
Update the link to the correct working link.

Update Langchain Links in the ipython notebook

---

generation/generative-qa/openai/gen-qa-openai/gen-qa-openai.ipynb

Fixed typo "enviroment" in gen-qa-openai.ipynb

---

pinecone/sparse/bm25/bm25-vector-generation.ipynb

BM25 vector generation notebook lack installation of torch and sentence transformers
Install sentence transformers and pytorch dependecies
Running notebooks

add pytorch dependency for bm25 generation notebook

---

search/semantic-search/semantic-search.ipynb

- Fixes the semantic search notebook to limit the dataset size to < 100k
- Makes the code consistent w/ other notebooks in how we initialize pinecone

cleanup + limit vector count to < 100k

---

generation/generative-qa/openai-ml-qa/01-making-queries.ipynb
generation/generative-qa/openai/gen-qa-openai/gen-qa-openai-fast.ipynb
generation/gpt4-retrieval-augmentation/gpt-4-langchain-docs-fast.ipynb
search/semantic-search/sparse/splade/splade-quora.md

There is a typo in the `environment` parameter name in some of the notebooks. Thanks @yaakovs to point it out.
@jhamon note that having a default value in the environment parameter ("us-west1") can cause troubles, especially when the user have a typo in the parameter name + we don't throw error on unrecognized parameter. 
Fix the typo
Manually test with non-default environments

fix typo in env argument

---

README.md

Add a simple root README to greet users with a little eye candy and relevant links. 
I mostly copied the same look and feel from `./learn` while linking off to the `./learn` README as made sense to me. 
Rendered locally and spot checked with `gh markdown-preview`.

Add README.md to repo root

---

learn/README.md

We've got a new YouTube video that walks folks through the basics of loading and using Jupyter Notebooks. This pull request uses the YouTube image trick (loading the first frame of a video as an image) in order to create an image link to the video itself, since it's unfortunately impossible to embed the video itself within a GitHub README.
Here's [a direct link](https://github.com/zackproser/examples/blob/a262a4e85a350da66736fe98b611718fff1c1247/learn/README.md) to the rendered, updated README for ease of review.
I validated this change locally with `gh markdown-preview` …

Add an image link to the YouTube video walkthrough for Notebooks

---

learn/generation/langchain/handbook/xx-langchain-chunking.ipynb

OpenAI is deprecating several legacy models on January 4th, 2024, which we are still referencing in this Notebook.
Remove the markdown table referencing deprecated OpenAI models. Update info to reflect which models remain supported currently.
This was verified via the Preview interface on GitHub

Remove markdown table of deprecated OpenAI models

---

integrations/openai/beyond_search_webinar/app.py

-Previously referenced models are deprecated by OpenAI
OpenAI is deprecating many legacy models per: https://openai.com/blog/gpt-4-api-general-availability as of January, 4th 2024.
Update references in this Notebook so that they point at the latest stable models offered by OpenAI.

Update references to point to current models

---

learn/generation/langchain/managing_rag_docs_langchain.ipynb

By default LangChain generates random UUIDs for vectors. This makes it difficult for users to, for example, update all vectors pertaining to a particular document (especially on Serverless).
Specify custom IDs with [prefixes](https://docs.pinecone.io/guides/data/manage-rag-documents)
tested in Colab
---
- https://app.asana.com/0/0/1207384414230752

Create example notebook for using ID prefixes with LangChain

---

learn/generation/pinecone-assistant/assistants-ai-demo.ipynb

There's a bug in earlier versions of the `pinecone-plugin-assistant` library that incorrectly throws errors, suggesting the user's Pinecone API key is invalid.
Update the `pinecone-plugin-assistant` to `0.1.3`.
We've validated this fix via Google Colab.

Bump pinecone-plugin-assistant to 0.1.3

---

docs/pinecone_reranker.ipynb

Reranker notebook is missing the colab and nbviewer widgets.
Add them.

Add colab and nbviewer widgets to reranker notebook

---

docs/gen-qa-openai.ipynb

The current model in the notebook `gpt-3.5-turbo-0613` is deprecated, so the notebook does not run. 
OpenAI [suggests switching to GPT-4o mini](https://platform.openai.com/docs/models/gpt-3-5-turbo), so I swapped to that and pinned it to a specific version (`gpt-4o-mini-2024-07-18`) for consistency. We can also use `gpt-4o-mini` which will automatically update versions. 
I ran the notebook using the [internal workflow](https://github.com/pinecone-io/pinecone-db/actions/runs/10951860458), and it passed.

Update gpt model to 4o-mini in gen-qa-openai.ipynb

---

docs/pinecone-bulk-import.ipynb

We're not using the term "bulk import" anymore, so this PR renames the index from `pinecone-bulk-import1-1024-1` to `pinecone-import1-1024-1`.

Rename index in import notebook

---

.github/scripts/version-census.py
.github/workflows/client-versions.yaml
pyproject.toml
uv.lock

We need to a way to identify which notebooks are out of date.
- Add a workflow script that prints a report of pinecone version usage on every push to CI.
- It also assess plugin usage

Add a report of Pinecone client library usage

---

learn/experimental/algos-and-libraries/offline-evaluation/offline-evaluation.ipynb

It appears that links got broken when this algos-and-libraries directory got moved without updating image links inside the notebooks
Adjust paths

Fix broken image links in offline-evaluation notebook

---

.github/actions/check-links/action.yml
.github/actions/check-links/check-links.py
.github/workflows/test-notebooks-changed.yaml
docs/langchain-retrieval-agent.ipynb

Some notebooks contain broken links
When someone is working on a notebook, we want to ensure all links are valid. Parse out the links, then do a `HEAD` request to see if they are valid.

Verify links when notebooks are changed

---

learn/generation/langchain/rag-chatbot.ipynb
learn/search/semantic-search/hello-pinecone-aws.ipynb

Updates outdated models and Q&A from old RAG chatbot notebook. Also updates the `langchain-pinecone` package to the latest version `0.2.5`

feat: update rag chatbot notebook

---

.github/workflows/post-merge.yaml

We only want to trigger post-merge actions on some files
Implement a `DIFF_WHITELIST` env variable that is used to limit the output from `git diff`
These git commands are using the feature that allows paths to be specified as positional arguments after `--`

Add files whitelist to change detection

---

learn/generation/langchain/rag-sparse-query-expansion.ipynb

Showcase the use of Pinecone sparse embeddings and sparse indexes for in situations where dense vector search might miss specific technical terms.
- use Pinecone sparse embeddings
- use query expansion technique
- allow Langchain agent to search for specific technical terms from general queries ("Which tech companies were top performers this week?" transforms into vector search about "GOOGL performance", "NVIDIA Performance", ...
---------

chore: performing sparse search with query expansion in langchain (#443)

---

learn/generation/langchain/handbook/02-langchain-chains.ipynb
learn/generation/langchain/handbook/03-langchain-conversational-memory.ipynb

Changes:
- Import `langchain-community` as it's required for `from langchain.callbacks import get_openai_callback`.
- Import `numexpr` as it's required by `LLMMathChain`.
- Updated to use LCEL, rather than importing Chain classes.
- Removed LangChain Hub part at end of Notebook as it was used for importingt the deprecated LLMathChain

fix: Updated learn\generation\langchain\handbook\02-langchain-chains.ipynb to Work with LangChain 0.3

---

learn/generation/langchain/handbook/01-langchain-prompt-templates.ipynb

Had to change the example from prompting the LLM to make jokes in response to serious questions, to a Markdown formatting task, as newer LLMs are too good at following orders and the supposedly bad responses were not actually bad.

fix: updated lc handbook 01

---

learn/generation/langchain/handbook/02-langchain-chains.ipynb
learn/generation/langchain/handbook/03-langchain-conversational-memory.ipynb

Changes:
- Import `langchain-community` as it's required for `from langchain.callbacks import get_openai_callback`.
- Import `numexpr` as it's required by `LLMMathChain`.
- Updated to use LCEL, rather than importing Chain classes.
- Removed LangChain Hub part at end of Notebook as it was used for importingt the deprecated LLMathChain

fix: update lc handbook 02

---

docs/semantic-search.ipynb

An earlier change to the semantic search notebook broke functionality, by causing a new version of numpy to be installed (2.3.2), which broke the datasets library's install of tatoeba. This commit pins numpy to an earlier version (2.0.2) that allows for the notebook to run as intended.
I tested between colab and local frequently, and found that colab's UV instance has numpy 2.3.2, whereas their pip instance has 2.0.2. Pip did not experience this issue install when using datasets previously, so I tested pinning the uv install of numpy to 2.0.2, which worked on:
- the colab instance
- an uploaded local instance to colab as …

Pinned Numpy Version to avoid conflicts with Datasets in semantic-search notebook

---

docs/cascading-retrieval.ipynb
docs/lexical-search.ipynb

Added:
- lexical search notebook
- cascading retrieval notebook

Search notebooks
