article_recommender/article_recommendations.ipynb
This notebook was not previously uploaded to the examples repository, so I created a folder and uploaded the notebook with an updated Python client. I used the `articles_simple_graph.ipynb` notebook from the `smartcat-pinecone-repo`.
Also, just to mention that using the ` environment='us-west1-gcp'` doesn't work for me, it produces the `UnauthorizedException: (401)`, so during the testing, I used the  ` environment='internal-beta'`, and replace it at the end with the  ` environment='us-west1-gcp'` .
=> update article recommendation notebook

locality_sensitive_hashing_traditional/sparse_implementation.ipynb
Small correction in "create_hash_func"
=> Use size-parameter passed to create_hash_func

integrations/haystack/README.md, integrations/haystack/haystack_lfqa.ipynb, integrations/haystack/lfqa/haystack_lfqa.ipynb
=> added notebook for LFQA with PineconeDocumentStore

generation/langchain/handbook/02-langchain-chains.ipynb
Added 'chains' notebook for langchain handbook
=> added langchain chains notebook

generation/langchain/handbook/05-langchain-retrieval-augmentation-fast.ipynb, generation/langchain/handbook/05-langchain-retrieval-augmentation.ipynb, generation/langchain/handbook/08-langchain-retrieval-agent.ipynb
=> fixes and install changes

generation/generative-qa/openai/gen-qa-openai/gen-qa-openai-fast.ipynb, generation/generative-qa/openai/gen-qa-openai/gen-qa-openai.ipynb, generation/gpt4-retrieval-augmentation/gpt-4-langchain-docs-fast.ipynb, generation/gpt4-retrieval-augmentation/gpt-4-langchain-docs.ipynb
=> New fast generation

generation/chatbots/chatbot.ipynb
=> added sleep time to chatbot

generation/llama-index/llama-index-intro.ipynb
=> remove namespace from llama-index notebook

generation/langchain/handbook/05-langchain-retrieval-augmentation-fast.ipynb
There was a version mismatch between pinecone-client and pinecone-datasets libraries which caused errors in the notebook execution.
Removed specific version of the pinecone-datasets library and used latest instead.
Testing should be done with the pinecone-notebook-tests suite after being granted access.
=> Langchain 05 fast example fix 

generation/langchain/handbook/08-langchain-retrieval-agent-fast.ipynb
Created a new "fast" version of the [LangChain retrieval agent notebook](https://github.com/pinecone-io/examples/blob/langchain-08-retrieval-agent-fast/generation/langchain/handbook/08-langchain-retrieval-agent.ipynb.)
Prepared a precomputed dataset and loaded it from the `pinecone-datasets` library, then followed the logic from the original notebook.
=> Langchain 08 retrieval agent fast

recommendation/audio-recommender/audio-recommendation.ipynb
=> updated location

generation/langchain/handbook/09-azure-openai-retrieval.ipynb
=> added new azure notebook

generation/langchain/handbook/09b-azure-openai-simple.ipynb
=> added simple azure example

learn/generation/chatbots/nemo-guardrails/02-rag-with-actions/02-rag-with-actions.ipynb
Making 02 guardrails notebook better
=> updated guardrails 02 notebook

learn/generation/chatbots/nemo-guardrails/01-variables-and-flows.ipynb, learn/generation/chatbots/nemo-guardrails/02-colang-actions.ipynb, learn/generation/chatbots/nemo-guardrails/02a-actions-weather-api.ipynb, learn/generation/chatbots/nemo-guardrails/03-rag-with-actions.ipynb, learn/generation/llm-field-guide/open-llama/retrieval-augmentation-open-llama-langchain.ipynb
=> updated shields and added new weather example

learn/generation/aws/sagemaker/sagemaker-pinecone-rag.ipynb
=> add aws rag notebook

learn/generation/chatbots/nemo-guardrails/00-intro/00-intro.ipynb, learn/generation/chatbots/nemo-guardrails/00-intro/config/topics.co, learn/generation/chatbots/nemo-guardrails/02-colang-actions.ipynb
=> new intro and 02 tweaks

learn/generation/aws/sagemaker/sagemaker-huggingface-rag.ipynb, learn/generation/aws/sagemaker/sagemaker-llama-2-rag.ipynb
=> added new notebook and updated HF notebook name

learn/generation/aws/sagemaker/sagemaker-huggingface-rag.ipynb, learn/generation/aws/sagemaker/sagemaker-llama-2-rag.ipynb
=> added sagemaker buttons

learn/generation/openai/fine-tuning/gpt-3.5-agent-training/chains.py
=> added fine-tuning chains file

learn/generation/openai/fine-tuning/gpt-3.5-agent-training/00-fine-tuning.ipynb
=> added fine-tuning notebook

learn/generation/langchain/handbook/06-langchain-agents.ipynb
Solution to the open issue: https://github.com/pinecone-io/examples/issues/180
Changed the usage of `SQLDatabaseChain` due to LangChain updates.
=> Solution to the open issue - Updated 06-langchain-agents.ipynb example

learn/generation/langchain/rag-chatbot.ipynb
=> added rag chatbot notebook

docs/semantic-search.ipynb
Fix for the open issue: https://github.com/pinecone-io/examples/issues/271
Changed the reference notebook link inside the example notebook.
=> Fix notebook reference link

docs/it-threat-detection.ipynb, docs/langchain-retrieval-agent.ipynb
Making changes in the notebooks to make them pass the test automation pipeline.
Change method for retrieving env variables, from `os.getenv` to `os.environ.get`.
=> /docs notebook examples fixes

learn/search/semantic-search/hello-pinecone-aws.ipynb
=> aws 101 notebook

learn/generation/langchain/handbook/10-langchain-multi-query.ipynb
=> add output to multiquery notebook

learn/search/semantic-search/2311-embedding-examples/retrieval-perf-voyage-01.ipynb
=> new voyage 01 example

learn/generation/langchain/handbook/11-langchain-expression-language.ipynb
New LangChain Expression Language example
=> added new LCEL notebook

learn/generation/llm-field-guide/mistral-ai/mixtral-8x7b/00-mixtral-8x7b-agent.ipynb
=> added mixtral agent notebook

docs/langchain-retrieval-augmentation.ipynb, learn/generation/chatbots/chatbot.ipynb
import fixes for langchain notebooks
=> fixes to imports

learn/search/semantic-search/deduplication/deduplication_scholarly_articles.ipynb
The notebook does not work with the new API and uses a pod-based index.
I modified the notebook to use a serverless index. The client initialization is modified to use the new API. I ran all cells to validate the notebook works out of the box, and everything appears fine, although I had to run the "# Query the vector index" cell a second time for it to work on my second end-to-end run through the notebook. I also moved the markdown cell that prompts a user to get an API key if they don't have one to above the code cell that initializes the client.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
The reviewer should run the updated version of the notebook end-to-end.
=> modify tutorial for serverless

learn/generation/langchain/v1/xml-agents.ipynb
Adding new agents example for Langchain v1, focusing on XML Agents with Pinecone, Anthropic, and Cohere.
=> add example for xml agents

learn/generation/canopy/canopy-azure-openai-studio/canopy-azure-openai.ipynb
Img path was broken due to a last-minute re-architecture.
=> Fix img path in Canopy Azure OpenAI Studio nb

docs/gen-qa-openai.ipynb
Fixes https://app.asana.com/0/1206419570114940/1206221687573157/f
=> Fix self-referential link in openai notebook

learn/generation/better-rag/03-ragas-evaluation.ipynb
=> add ragas notebook

learn/generation/langchain/v1/claude-3-agent.ipynb
Add example for Claude 3 agent using Voyage AI and Pinecone for RAG component
_Cannot merge until LangChain releases [update to their Anthropic agents](https://github.com/langchain-ai/langchain/pull/18630)_
=> add claude 3 agent example

learn/generation/langchain/langgraph/00-langgraph-intro.ipynb
=> add langgraph intro notebook

learn/generation/langchain/handbook/01-langchain-prompt-templates.ipynb
fix typo exerpts --> excerpts
Typo in prompt
Fix typo in prompt
=> fix typo in prompt

docs/pinecone-quickstart.ipynb
Forgot to add colab/notebook buttons to the new quickstart notebook.
Add the buttons. 
=> Add colab/notebook buttons to quickstart notebook

learn/generation/langchain/langgraph/01-gpt-4o-research-agent.ipynb
=> feat: new research agent example

docs/pinecone-quickstart.ipynb
Previous version of doc example was not passing notebook tests
* Added separate cell for `index_name` definition so testing framework can identify the index being created
* Added a few `time.sleep` functions and a wait for the index to be ready to avoid errors stemming from index not being ready to query/use
=> fix: tweak for alignment with required nb testing framework

integrations/groq/groq-llama-3-rag.ipynb
=> feat: new groq llama 3 example

docs/pinecone-quickstart.ipynb
=> fix: test diff authenticate method

docs/pinecone-quickstart.ipynb
=> fix: colab auth import

learn/search/hybrid-search/ecommerce-search/ecommerce-search.ipynb
add Connect widget to make it easier for users to run the notebook
https://docs.pinecone.io/integrations/build-integration/connect-your-users-to-pinecone#colab
tested in Colab
---
- https://app.asana.com/0/0/1207488258520668
=> add connect widget

learn/experimental/merge-namespaces/merge-namespaces.ipynb
[forum post](https://community.pinecone.io/t/does-pinecone-support-merging-namespace/5774)
Adapted code given in forum post
tested in colab
---
- https://app.asana.com/0/0/1207498436939808
=> Create colab notebook for merging two namespaces

learn/generation/pinecone-assistant/assistants-ai-demo.ipynb
=> feat: new assistant notebook

learn/generation/langchain/langgraph/01-gpt-4o-research-agent.ipynb
Improvements to research agent example and upgrade to langchain v2
=> feat: simplify code and upgrade to langchain v2

docs/rag-getting-started.ipynb
- typo
- cell output showing error
- fixed
- removed
tested in colab
=> fix small issues in rag-chatbot notebook

learn/assistant/pinecone-assistant-getting-started.ipynb
Beta warning no longer applies
remove warning
N/A
=> remove note about Assistant beta

learn/search/semantic-search/semantic-search.ipynb
Dependencies in this notebook are out of date, and we want to showcase the use of Pinecone Inference.
These changes: 
- Update `pinecone-client` to `5.0.1`
- Update the `datasets` dependency to `2.14.6`
- Swap out the `MiniLM-L6` model for Pinecone Inference and `multilingual-e5-large`
=> Update semantic-search notebook to use PC inference

docs/pinecone-bulk-import.ipynb
We don't have a notebook featuring bulk import. 
Adding a bulk import notebook, authored by Rick.
=> Add bulk import notebook

learn/generation/better-rag/xx-unstructured-pdf-elements.ipynb
=> feat: unstructured example

learn/generation/better-rag/00-rerankers-pinecone.ipynb
=> fix: use query embeddings correctly

learn/generation/better-rag/00-rerankers-pinecone.ipynb
=> fix: rerankers cleanup

learn/generation/llama-index/llama_index_research_agent_condensed.ipynb
Existing workflow notebook needed some changes to make easier to run
- added pinecone connect
- added colab notebook
- removed dependencies to semantic router and serpapi
- typos
- rewrote some functions to use llamaindex embedding from openai directly
- 
- [ x] New feature (non-breaking change which adds functionality)
Run through the notebook in colab
=> Llamaindex Workflows Example for 10/11 Hackathon

docs/rag-getting-started.ipynb
Some parts of the tutorial are under-explained.
Fix this based on input from @krugster. 
=> RAG chatbot notebook improvements from Perry

docs/pinecone-import.ipynb
=> Fix colab links

docs/pinecone-quickstart.ipynb
Use inference embedding
---
- https://app.asana.com/0/0/1208649234054644
=> Update quickstart notebook to mirror docs quickstart

docs/pinecone-quickstart.ipynb
We updated our docs quickstart to use a different dataset and to include filtering and reranking. The corresponding notebook needs to be updated accordingly.
Update the notebook to match the docs quickstart.
=> Update quickstart notebook to match updated docs quickstart

docs/pinecone-quickstart.ipynb
=> Quickstart notebook tweaks to align with docs quickstart

.github/scripts/validate-notebook-formats.py, .github/workflows/validate.yaml, learn/assistant/pinecone-assistant-getting-started.ipynb
A notebook was accidentally committed with syntax errors that prevent it from being viewed or run.
- Add a test workflow to ensure all notebooks contain valid json on every commit.
- Fix the broken notebook
If you commit a notebook with broken JSON formatting, you will now see a failed workflow with error message like this:
=> Add github workflow to check notebook syntax is valid json

docs/pinecone-quickstart.ipynb
Quickstart notebook is out-of-sync with the quickstart in our docs.
Update the quickstart notebook.
- New dataset
- Uses integrated embedding and reranking
- Links to other resources for improving results
=> Update quickstart notebook to match the quickstart doc

.github/actions/validate-json/validate-notebook-formats.py, .github/scripts/version-census.py, .github/workflows/client-versions.yaml, .github/workflows/pr.yaml, docs/quick-tour/hello-pinecone.ipynb, docs/quick-tour/interacting-with-the-index.ipynb, docs/quick-tour/metadata-filtering.ipynb, docs/quick-tour/namespacing.ipynb, pyproject.toml
Some notebooks contain broken links
Fix them
=> Update links in docs/quick-tour notebooks

.github/actions/post-merge-additions/action.yml, .github/actions/post-merge-additions/process-additions.py, .github/actions/post-merge-deletions/action.yml, .github/actions/post-merge-deletions/process-deletions.py, .github/actions/post-merge-modifications/action.yml, .github/actions/post-merge-modifications/process-modifications.py, .github/workflows/post-merge.yaml
We would like to trigger some actions based on changes to this repository
Introduce a new workflow that is run whenever changes are merged to `master` branch (the default branch). The workflow is defined in `.github/workflows/post-merge.yaml` and uses git with `diff-filter`s to group changes by whether they are additions, deletions, or modifications. Then it invokes specific actions to handle each type of change, although for now these actions are just stubs. More work will be needed to implement the real contents of each action.
- The names of added notebooks are passed to the `.github/actions/post-merge-additions/process-additions.py` script.
- The names of removed notebooks are passed to the `.github/actions/post-merge-deletions/process-deletions.py` script
- The names of changed …
=> Add workflow to process changes after merge to master

docs/pinecone-quickstart.ipynb
Want to make it easier to track indexes created from this notebook.
Use a unique index name to make tracking easier. 
=> Update index name in quickstart notebook

learn/search/meeting-transcription-search/meeting_transcription_semantic_search.ipynb
A new sample notebook requested internally for meeting transcription. Super simple, uses Hugging Face, Whisper and pinecone's integrated inference for semantic search.
---
- https://app.asana.com/0/0/1210038526369577
=> Meeting Transcription Notebook

docs/semantic-search.ipynb
The prior semantic search notebook was outdated and demonstrated many patterns that are easier to do in Pinecone natively now. Additionally, the notebook was lengthy and indexed a TON of vectors that took a while to demonstrate.  We need a faster notebook more in line with modern practices with Pinecone.
- Replaced sentence transformers with Pinecone Integrated Inference
- Replaced lengthy dataset with a smaller, more instructive one. The smaller dataset also can easily be modified for a larger subset if a user desires
- Better API key handling for colab or local development
- Should be much faster in CI/CD/Github Actions …
=> Refresh Semantic Search Docs Example

docs/semantic-search.ipynb
Replace me5 with llama per tej request
=> Adding llama instead of e5 to notebook

docs/semantic-search.ipynb
Source tags need to use _ not -.
=> Change source tag to use _

learn/generation/langchain/handbook/06-langchain-agents.ipynb
=> improve: Updated Notebook learn\generation\langchain\handbook\06-langchain-agents.ipynb

learn/generation/langchain/handbook/05-langchain-retrieval-augmentation.ipynb
…chain-retrieval-augmentation.ipynb (#476)
Now runs successfully and is up to date with latest LCEL methods.
=> chore: updated langchain handbook ch5

learn/generation/langchain/handbook/05-langchain-retrieval-augmentation.ipynb
…ipynb (#479)
Previously this code assumed the LLM couldn't do maths, which is now an outdated assumption. Also it assumed the LLM wouldn't use the tools provided unless given very clear instructions which is no longer the case. Updated to be more in line with modern LangChain practices, including using LCEL.
=> chore: update langchain handbook ch7

.github/actions/run-notebook/action.yml, .github/workflows/test-notebooks-all.yaml, .github/workflows/test-notebooks-changed.yaml, learn/generation/traditional-rag/traditional-rag-with-claude-and-hybrid.ipynb
Add ANTHROPIC_API_KEY for notebook runs - to coincide with adding secret to github settings in this repo
=> Add ANTHROPIC_API_KEY for notebook runs

learn/generation/better-rag/02b-semantic-chunking.ipynb
=> Fix Colab Button to Redirect to Colab

docs/semantic-search.ipynb
Replaced current install pattern with UV for a much faster experience. Added text around how API keys work to see how that affects completion rates.
=> Update Semantic Search Example to use UV and better explain API keys
